[[redirects]]
from = "https://djseanzie.com/*"
to = "https://djseanzie.club/:splat"
status = 301
force = true
[[redirects]]
from = "https://www.djseanzie.com/*"
to = "https://djseanzie.club/:splat"
status = 301
force = true
[[redirects]]
from = "https://links.djseanzie.com/*"
to = "https://links.djseanzie.club/:splat"
status = 301
force = true
[[redirects]]
from = "https://spotify.djseanzie.com/*"
to = "https://open.spotify.com/playlist/6dcgwhMSuUCO0U08QEcGxr?si=0419bc8c5cc74ec0"
status = 301
force = true
[[redirects]]
from = "https://spotify.djseanzie.club/*"
to = "https://open.spotify.com/playlist/6dcgwhMSuUCO0U08QEcGxr?si=0419bc8c5cc74ec0"
status = 301
force = true