[[redirects]]
from = "https://djseanzie.com/*"
to = "https://djseanzie.club/:splat"
status = 301
force = true
[[redirects]]
from = "https://djseanzie.com/*"
to = "https://djseanzie.club/:splat"
status = 301
force = true
[[redirects]]
from = "https://djseanzie.com/*"
to = "https://djseanzie.club/:splat"
status = 301
force = true
[[redirects]]
from = "https://djseanzie.com/*"
to = "https://djseanzie.club/:splat"
status = 301
force = true