[[redirects]]
from = "https://djseanzie.com/*"
to = "https://djseanzie.club/:splat"
status = 301
force = true
[[redirects]]
from = "https://www.djseanzie.com/*"
to = "https://djseanzie.club/:splat"
status = 301
force = true
[[redirects]]
from = "https://links.djseanzie.com/*"
to = "https://links.djseanzie.club/:splat"
status = 301
force = true
[[redirects]]
from = "https://www.links.djseanzie.com/*"
to = "https://links.djseanzie.club/:splat"
status = 301
force = true